trigger:
  branches:
    include:
    - master
variables:
- name: Test
    value: mytest
stages:
- stage: __default
    jobs:
    - job: Job
    pool:
        vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
        displayName: Run a one-line script
        inputs:
        script: echo Hello Devops, world!
    - task: CmdLine@2
        displayName: Create a test file $(Test)
        inputs:
        script: >
            echo "Hello Devops World in a YAML Pipeline" > "$PIPELINE_WORKSPACE/outputfile.txt"
